apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 138778713921.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 138778713921.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
